version: '3'

services:
  nginx:
    image: viniciusmattosrj/nginx
    container_name: nginx_projetos
    restart: always
    volumes:
     - ./config/nginx_conf/:/etc/nginx/conf.d
    depends_on:
     - php
    networks:
      projetos_servicos:
        ipv4_address: 10.11.0.10

  php: #php7.1.15
    image: viniciusmattosrj/php:7.1
    container_name: php
    restart: always
    command: bash -c "sed -i \"s/memory_limit = 128M/memory_limit = 1024M/\" /usr/local/etc/php/php.ini
                      && sed -i \"s/register_argc_argv = Off/register_argc_argv = On/\" /usr/local/etc/php/php.ini
                      && sed -i \"s/max_execution_time = 30/max_execution_time = 9999/\" /usr/local/etc/php/php.ini
                      && sed -i \"s/upload_max_filesize = 2M/upload_max_filesize = 30M/\" /usr/local/etc/php/php.ini
                      && sed -i \"s/short_open_tag = Off/short_open_tag = On/\" /usr/local/etc/php/php.ini
                      && sed -i \"s/;date.timezone =/date.timezone = America\/Sao_Paulo/\" /usr/local/etc/php/php.ini
                      && sed -i \"s/post_max_size = 8M/post_max_size = 30M/\" /usr/local/etc/php/php.ini
                      && sed -i \"s/xdebug.remote_port=9001/xdebug.remote_port=9000/\" /usr/local/etc/php/conf.d/ext-xdebug.ini
                      && sed -i \"s/xdebug.remote_connect_back = Off/xdebug.remote_connect_back = On/\" /usr/local/etc/php/conf.d/ext-xdebug.ini
                      && sed -i \"s/xdebug.idekey=docker/xdebug.idekey=/\" /usr/local/etc/php/conf.d/ext-xdebug.ini
                      && php-fpm"
    environment:
     - XDEBUG_CONFIG=remote_host=172.17.0.1
     - PHP_IDE_CONFIG=serverName=Local
    volumes:
     - ./:/var/www/html
     - ~/.ssh:/root/.ssh
    networks:
      projetos_servicos:
        ipv4_address: 10.11.0.11

networks:
  projetos_servicos:
   external: true