version: '3'

services:
#  nginx:
#    image: viniciusmattosrj/nginx
#    container_name: nginx_projetos
#    restart: always
#    volumes:
#     - ./config/nginx_conf/:/etc/nginx/conf.d
#    depends_on:
#     - php
#    networks:
#      working_servicos:
#        ipv4_address: 10.11.0.10

  php: #php7.3.22
    image: viniciusmattosrj/php:7.3
    container_name: php_pdo
    restart: always
    environment:
      - XDEBUG_CONFIG=remote_host=172.17.0.1
      - PHP_IDE_CONFIG=serverName=Local
    volumes:
     - ./:/var/www/html
     - ~/.ssh:/root/.ssh
    networks:
      working_servicos:

networks:
  working_servicos:
   external: true